---
version: 2

unit_tests: &unit_tests
  - run: apt-get -y update && apt-get -y install git
  - checkout
  - run: >
      curl -o- 'https://getcomposer.org/installer' |
      php -- --quiet --filename=composer --install-dir=/usr/local/bin
  - run: composer install
  - run: php tests/run.php unit

all_tests: &all_tests
  - checkout
  - run: composer install
  - run: php tests/run.php unit e2e
  - run: vendor/bin/codacycoverage clover ./coverage.xml

jobs:
  php-5.4:
    docker:
      - image: thiagoalessio/php:5.4
    steps:
      - checkout
      - run: composer install
      - run: php tests/run.php unit

  php-5.6:
    docker:
      - image: php:5.6
    steps: *unit_tests

  php-7.0:
    docker:
      - image: php:7.0
    steps: *unit_tests

  php-7.1:
    docker:
      - image: php:7.1
    steps: *unit_tests

  php-7.2:
    docker:
      - image: php:7.2
    steps: *unit_tests

  php-7.3:
    docker:
      - image: php:7.3
    steps: *unit_tests

  php-7.4:
    docker:
      - image: php:7.4
    steps: *unit_tests
    
  php-8.0:
    docker:
      - image: php:8.0.0
    steps: *unit_tests

  tess-3.02:
    docker:
      - image: thiagoalessio/tesseract:3.02
    steps: *all_tests

  tess-3.03:
    docker:
      - image: thiagoalessio/tesseract:3.03
    steps: *all_tests

  tess-3.04:
    docker:
      - image: thiagoalessio/tesseract:3.04
    steps: *all_tests

  tess-3.05:
    docker:
      - image: thiagoalessio/tesseract:3.05
    steps: *all_tests

  tess-4.00:
    docker:
      - image: thiagoalessio/tesseract:4.00
    steps: *all_tests

php_jobs: &php_jobs
  - php-5.4
  - php-5.6
  - php-7.0
  - php-7.1
  - php-7.2
  - php-7.3
  - php-7.4
  - php-8.0

workflows:
  version: 2
  default:
    jobs:
      - php-5.4
      - php-5.6
      - php-7.0
      - php-7.1
      - php-7.2
      - php-7.3
      - php-7.4
      - php-8.0
      - tess-3.02:
          requires: *php_jobs
      - tess-3.03:
          requires: *php_jobs
      - tess-3.04:
          requires: *php_jobs
      - tess-3.05:
          requires: *php_jobs
      - tess-4.00:
          requires: *php_jobs

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/2a55ca057ba4a0b16123
